dist: trusty
sudo: false
language: node_js
node_js: "8.7"
cache: 
  directories:
    - node_modules
script:
- travis_fold:start:npmls
- npm ls
- travis_fold:end:npmls
- "npm test"
- "npm run lint"
before_deploy:
- "npm run build"
deploy:
  provider: pages
  local_dir: "dist"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
